apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backstage-db-secret
  namespace: backstage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: postgres-secrets
    template:
      data:
        POSTGRES_USER: "{{ .username }}"
        POSTGRES_PASSWORD: "{{ .password }}"
        POSTGRES_HOST: "127.0.0.1" # Sidecar Proxy
  data:
  - secretKey: username
    remoteRef:
      key: backstage-db-username
  - secretKey: password
    remoteRef:
      key: backstage-db-password
