apiVersion: v1
kind: ServiceAccount
metadata:
  name: payment-sa
  namespace: nexus-app
  annotations:
    iam.gke.io/gcp-service-account: opsnexus-payment-sa@dotted-saga-493511-a1.iam.gserviceaccount.com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storefront-payment
  namespace: nexus-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storefront-payment
  template:
    metadata:
      labels:
        app: storefront-payment
        app.kubernetes.io/part-of: storefront
      annotations:
        sidecar.istio.io/proxyCPU: "100m"
        sidecar.istio.io/proxyCPULimit: "500m"
        sidecar.istio.io/proxyMemory: "128Mi"
        sidecar.istio.io/proxyMemoryLimit: "512Mi"
    spec:
      serviceAccountName: payment-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      volumes:
      - name: tmp
        emptyDir: {}
      containers:
      - name: payment
        image: storefront-payment
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
        env:
        - name: GCP_SECRET_NAME
          value: "payment-api-key"
        - name: GOOGLE_CLOUD_PROJECT
          value: "dotted-saga-493511-a1"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: storefront-payment
  namespace: nexus-app
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: storefront-payment
