apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  profile:
    displayName: Guest User
    email: guest@example.com
    picture: https://avatars.githubusercontent.com/u/0?v=4
  memberOf: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: ayush-gharat
spec:
  profile:
    displayName: Ayush Gharat
    email: ayushgharat234@gmail.com
    picture: https://api.dicebear.com/7.x/avataaars/svg?seed=Ayush
  memberOf: [sre-team, idp-team]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: dev-bob
spec:
  profile:
    displayName: Bob Builder
    email: bob@dhi.io
    picture: https://api.dicebear.com/7.x/avataaars/svg?seed=Bob
  memberOf: [payment-service-team]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: dev-alice
spec:
  profile:
    displayName: Alice Logistics
    email: alice@dhi.io
    picture: https://api.dicebear.com/7.x/avataaars/svg?seed=Alice
  memberOf: [logistics-team]