apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xstoragebuckets.dhi.io
spec:
  group: dhi.io
  names:
    kind: XStorageBucket
    claimKind: StorageBucket
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              location:
                type: string
                default: "US"
              versioning:
                type: boolean
                default: true
