apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-github-webhook
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: argocd-webhook
    template:
      data:
        webhook.github.secret: "{{ .webhook_secret }}"
  data:
  - secretKey: webhook_secret
    remoteRef:
      key: argocd-webhook-secret
