apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../frontend/kubernetes.yaml

images:
  - name: storefront-frontend
    newName: us-central1-docker.pkg.dev/dotted-saga-493511-a1/opsnexus/storefront-frontend
