apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: catalog-pipeline
description: "storefront-catalog → EKS Spoke — canary 25→75→100%"
serialPipeline:
  stages:
  - targetId: eks-spoke
    profiles: [eks]
    strategy:
      canary:
        runtimeConfig:
          kubernetes:
            serviceNetworking:
              deployment: storefront-catalog
              service: storefront-catalog
        canaryDeployment:
          percentages: [25, 75]
