apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: frontend-pipeline
description: "storefront-frontend → GKE Spoke — standard deployment"
serialPipeline:
  stages:
  - targetId: gke-spoke
    profiles: [gke-frontend]
    strategy:
      standard:
        verify: false
