apiVersion: deploy.cloud.google.com/v1
kind: Automation
metadata:
  name: payment-pipeline/advance-canary
deliveryPipeline: payment-pipeline
suspended: false
serviceAccount: opsnexus-ci-sa@dotted-saga-493511-a1.iam.gserviceaccount.com
selector:
- target:
    id: gke-spoke
rules:
- advanceRolloutRule:
    id: advance-canary-phases
    sourcePhases: [canary-25, canary-75]
    wait: 10m
