apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: nexus-app
  annotations:
    configmanagement.gke.io/cluster-selector: selector-gcp
spec:
  mtls:
    mode: STRICT
  portLevelMtls:
    "80":
      mode: PERMISSIVE
    "8080":
      mode: PERMISSIVE
