apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: nexus-app-metrics
  namespace: nexus-app
  annotations:
    configmanagement.gke.io/cluster-selector: selector-gcp
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: storefront
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
