apiVersion: v1
kind: ResourceQuota
metadata:
  name: nexus-app-quota
  namespace: nexus-app
spec:
  hard:
    pods: "20"
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "8"
    limits.memory: 8Gi
    services.loadbalancers: "2"
    secrets: "20"
